In [1]:
import time
start_time=time.time()
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import os
import statsmodels.api as sm
import linmix
from scipy.stats import pearsonr
import math
import itertools
import json
from logerr import logify
from results import loadresults,loadresults2

In [2]:
a,b = loadresults('sample-names-corr','formal-names-corr','1sig')

In [3]:
a

,Region,s0 [RMS],s0+[RMS],s0-[RMS],s0 [FWHM],s0- [FWHM],s0+ [FWHM],bn,bn+,bn-
0,NGC 604,2.107818,0.790623,0.296285,1.216317,0.170971,0.456229,3.274804e-01,0.376394,0.203626
1,NGC 595,0.407243,0.339347,-0.036163,0.235000,-0.020868,0.195820,1.537175e+00,1.073819,0.375550
2,Hubble X,0.362383,0.185304,0.054562,0.351311,0.052895,0.179642,3.211300e-01,0.258794,0.141971
3,Hubble V,0.341152,0.354885,-0.024915,0.330728,-0.024154,0.344042,3.548363e-10,0.454831,-0.071981
4,30 Dor,0.157696,0.046843,0.019562,1.528771,0.189643,0.454117,6.155564e+00,0.893257,0.721896
5,Carina,0.007489,0.005873,0.004098,1.704157,0.932530,1.336508,2.256934e+00,1.441267,1.062473
6,NGC 346,0.111505,0.014526,0.008360,0.871755,0.065359,0.113563,8.402099e-01,0.038955,0.033389
7,M8,0.006984,0.000838,0.005015,2.708257,1.944719,0.324972,4.366590e-01,0.103940,0.162262
8,Orion,0.002030,0.000143,0.000100,2.399523,0.117872,0.169618,2.515480e-02,0.002672,0.002428

In [4]:
b

,Region,sig2,sig2+,sig2-,r0,r0+,r0-,m,m+,m-
0,NGC 604,85.868750,16.496228,4.190338,12.087616,2.857540,2.031752,0.775075,0.083881,0.166948
1,NGC 595,53.206356,2.675113,0.577691,11.211662,0.341687,0.464387,1.376368,0.034288,0.084945
2,Hubble X,14.812259,1.300753,0.269389,4.099418,0.159073,0.135068,1.016097,0.034877,0.113082
3,Hubble V,9.824044,1.894628,0.080919,3.561965,0.146501,0.647256,0.810433,0.026176,0.186914
4,30 Dor,297.536688,20.129857,8.083811,3.857852,0.502290,0.223425,0.851961,0.034487,0.074879
5,Carina,18.137617,0.752841,0.838441,0.550457,0.046570,0.032894,1.158353,0.144906,0.093970
6,NGC 346,33.022801,1.350080,0.703959,2.373683,0.149143,0.077528,0.956389,0.023103,0.037638
7,M8,7.385188,0.635802,0.367221,1.034714,0.117271,0.060315,1.263906,0.083826,0.108784
8,Orion,12.648003,0.396671,0.254400,0.067959,0.003222,0.002031,1.073374,0.015441,0.020723

In [5]:
a,b = loadresults2('sample-names-corr','formal-names-corr','LM')

In [6]:
a

,Region,s0 [RMS],s0+[RMS],s0 [FWHM],s0+ [FWHM],bn,bn+
0,NGC 604,2.107818,1.276000,1.216317,0.736316,3.274804e-01,0.380672
1,NGC 595,0.407243,0.209656,0.235000,0.120982,1.537175e+00,0.952484
2,Hubble X,0.362383,0.173768,0.351311,0.168458,3.211300e-01,0.333569
3,Hubble V,0.341152,0.294993,0.330728,0.285980,3.548363e-10,0.712798
4,30 Dor,0.157696,0.030939,1.528771,0.299933,6.155564e+00,0.803967
5,Carina,0.007489,1.191873,1.704157,271.233600,2.256934e+00,49.845536
6,NGC 346,0.111505,0.008015,0.871755,0.062660,8.402099e-01,0.027369
7,M8,0.006984,0.723727,2.708257,280.645435,4.366590e-01,4.099369
8,Orion,0.002030,0.000113,2.399523,0.133966,2.515480e-02,0.002331

In [7]:
b

     Region        sig2      sig2+         r0       r0+         m        m+
0   NGC 604   85.868750  20.921720  12.087616  2.276384  0.775075  0.302830
1   NGC 595   53.206356   1.976813  11.211662  0.368098  1.376368  0.061697
2  Hubble X   14.812259   0.783731   4.099418  0.199684  1.016097  0.076939
3  Hubble V    9.824044   0.798728   3.561965  0.348352  0.810433  0.115229
4    30 Dor  297.536688  13.314719   3.857852  0.331025  0.851961  0.053713
5    Carina   18.137617  14.621368   0.550457  0.273834  1.158353  0.723974
6   NGC 346   33.022801   0.714645   2.373683  0.078812  0.956389  0.021514
7        M8    7.385188   3.256220   1.034714  0.108941  1.263906  0.173140
8     Orion   12.648003   0.293203   0.067959  0.002348  1.073374  0.016727